name: ExtraTools
version: ${project.version}
author: Sfiguz7
description: A Slimefun4-Addon aimed at implementing useful tools
website: https://github.com/Sfiguz7/ExtraTools

main: me.sfiguz7.extratools.ExtraTools
depend: [Slimefun]

api-version: 1.18
